### ISSUE TITLE
Quickstart doesn't include an example of Blueprint; it assumes the Blueprint has already been created via API

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#361]
Path: /quickstart/deploying

**Comment by ashleygmulligan2** [comment]
You want the repl.it to show how you'd create the Workbook not via cURL? Would that help?

**Comment by Arsik36** [comment]
Yes, that would help a lot. For example, I am trying to organize my work in 1 file in VS code. In that file. I want to have my template (blueprint) and validations that belong to that template. Right now in that file I have my validations like this:

```
export default function (listener) {

  listener.use(
    recordHook('contacts', (record) => {
      const value = record.get('firstName')?.toString()
      if (value) {
        record.set('firstName', value.toLowerCase())
        return record
      }

      const validEmailAddress = /^[\w\d.-]+@[\w\d]+\.\w+$/
      let emailAddress = record.get('email');
      if (emailAddress) {
        if (!validEmailAddress.test(emailAddress)) {
          record.addError('email', 'Invalid email address');
          return record
        }
      }
    })
  )
```

But, before I write those validations I want to write my template structure. Current Quickstart shows me how to

- create a space
- create a template
- attach a template to a space

all in 1 cURL command. Instead of that command, it would really help to have an example how I can code these 3 commands on 1 file in VS Code, so that the file contains:
- code to create a space
- code to create a template
- attach a template to that space
- define validations on that template

This would be a golden start to share with a developer

**Comment by ashleygmulligan2** [comment]
Now that I have a space:configure in our quickstart, I think this is resolved
